<?php


namespace backend\models;

use common\traits\SoftDelete;
use common\traits\Restore;

class Comment extends \common\models\Post
{
    use SoftDelete;
    use Restore;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}